# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/qosm_settings_dialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_qosmDialogSettings(object):
    def setupUi(self, qosmDialogSettings):
        qosmDialogSettings.setObjectName(_fromUtf8("qosmDialogSettings"))
        qosmDialogSettings.resize(605, 377)
        qosmDialogSettings.setModal(True)
        self.verticalLayout_4 = QtGui.QVBoxLayout(qosmDialogSettings)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tabWidget = QtGui.QTabWidget(qosmDialogSettings)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabGeneral = QtGui.QWidget()
        self.tabGeneral.setObjectName(_fromUtf8("tabGeneral"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabGeneral)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(self.tabGeneral)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.generalCacheSize = QtGui.QLabel(self.tabGeneral)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generalCacheSize.sizePolicy().hasHeightForWidth())
        self.generalCacheSize.setSizePolicy(sizePolicy)
        self.generalCacheSize.setObjectName(_fromUtf8("generalCacheSize"))
        self.horizontalLayout_4.addWidget(self.generalCacheSize)
        self.generalClearCache = QtGui.QPushButton(self.tabGeneral)
        self.generalClearCache.setObjectName(_fromUtf8("generalClearCache"))
        self.horizontalLayout_4.addWidget(self.generalClearCache)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_7 = QtGui.QLabel(self.tabGeneral)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout.addWidget(self.label_7)
        self.generalCacheLocation = QtGui.QLineEdit(self.tabGeneral)
        self.generalCacheLocation.setObjectName(_fromUtf8("generalCacheLocation"))
        self.horizontalLayout.addWidget(self.generalCacheLocation)
        self.generalBrowse = QtGui.QPushButton(self.tabGeneral)
        self.generalBrowse.setObjectName(_fromUtf8("generalBrowse"))
        self.horizontalLayout.addWidget(self.generalBrowse)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.tabGeneral)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.generalMaxTiles = QtGui.QSpinBox(self.tabGeneral)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generalMaxTiles.sizePolicy().hasHeightForWidth())
        self.generalMaxTiles.setSizePolicy(sizePolicy)
        self.generalMaxTiles.setMinimumSize(QtCore.QSize(75, 0))
        self.generalMaxTiles.setMaximum(9999)
        self.generalMaxTiles.setObjectName(_fromUtf8("generalMaxTiles"))
        self.horizontalLayout_2.addWidget(self.generalMaxTiles)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.autoDownload = QtGui.QCheckBox(self.tabGeneral)
        self.autoDownload.setChecked(True)
        self.autoDownload.setObjectName(_fromUtf8("autoDownload"))
        self.verticalLayout_5.addWidget(self.autoDownload)
        spacerItem = QtGui.QSpacerItem(20, 119, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.tabWidget.addTab(self.tabGeneral, _fromUtf8(""))
        self.tabTiletypes = QtGui.QWidget()
        self.tabTiletypes.setObjectName(_fromUtf8("tabTiletypes"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabTiletypes)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tiletypesList = QtGui.QListWidget(self.tabTiletypes)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tiletypesList.sizePolicy().hasHeightForWidth())
        self.tiletypesList.setSizePolicy(sizePolicy)
        self.tiletypesList.setMaximumSize(QtCore.QSize(16777215, 150))
        self.tiletypesList.setObjectName(_fromUtf8("tiletypesList"))
        self.verticalLayout_2.addWidget(self.tiletypesList)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.tabTiletypes)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.tiletypesPattern = QtGui.QLineEdit(self.tabTiletypes)
        self.tiletypesPattern.setObjectName(_fromUtf8("tiletypesPattern"))
        self.horizontalLayout_3.addWidget(self.tiletypesPattern)
        self.tiletypeChange = QtGui.QPushButton(self.tabTiletypes)
        self.tiletypeChange.setEnabled(False)
        self.tiletypeChange.setObjectName(_fromUtf8("tiletypeChange"))
        self.horizontalLayout_3.addWidget(self.tiletypeChange)
        self.tiletypeRemove = QtGui.QPushButton(self.tabTiletypes)
        self.tiletypeRemove.setEnabled(False)
        self.tiletypeRemove.setObjectName(_fromUtf8("tiletypeRemove"))
        self.horizontalLayout_3.addWidget(self.tiletypeRemove)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.groupBox = QtGui.QGroupBox(self.tabTiletypes)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_3.addWidget(self.label_4)
        self.verticalLayout_2.addWidget(self.groupBox)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.tabWidget.addTab(self.tabTiletypes, _fromUtf8(""))
        self.tabLogs = QtGui.QWidget()
        self.tabLogs.setObjectName(_fromUtf8("tabLogs"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabLogs)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.logWhichLog = QtGui.QComboBox(self.tabLogs)
        self.logWhichLog.setObjectName(_fromUtf8("logWhichLog"))
        self.logWhichLog.addItem(_fromUtf8(""))
        self.logWhichLog.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.logWhichLog)
        self.logText = QtGui.QTextBrowser(self.tabLogs)
        self.logText.setObjectName(_fromUtf8("logText"))
        self.verticalLayout.addWidget(self.logText)
        self.tabWidget.addTab(self.tabLogs, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.button_box = QtGui.QDialogButtonBox(qosmDialogSettings)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.Reset|QtGui.QDialogButtonBox.RestoreDefaults)
        self.button_box.setObjectName(_fromUtf8("button_box"))
        self.verticalLayout_4.addWidget(self.button_box)

        self.retranslateUi(qosmDialogSettings)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("accepted()")), qosmDialogSettings.accept)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("rejected()")), qosmDialogSettings.reject)
        QtCore.QMetaObject.connectSlotsByName(qosmDialogSettings)

    def retranslateUi(self, qosmDialogSettings):
        qosmDialogSettings.setWindowTitle(_translate("qosmDialogSettings", "QOSM Settings", None))
        self.label_5.setText(_translate("qosmDialogSettings", "Tile cache:", None))
        self.generalCacheSize.setText(_translate("qosmDialogSettings", "calculating...", None))
        self.generalClearCache.setText(_translate("qosmDialogSettings", "Clear Cache", None))
        self.label_7.setText(_translate("qosmDialogSettings", "Cache location", None))
        self.generalBrowse.setText(_translate("qosmDialogSettings", "Browse...", None))
        self.label.setText(_translate("qosmDialogSettings", "Max tiles to render at once", None))
        self.autoDownload.setText(_translate("qosmDialogSettings", "Automatically download new tiles", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGeneral), _translate("qosmDialogSettings", "General", None))
        self.label_3.setText(_translate("qosmDialogSettings", "URL Pattern", None))
        self.tiletypeChange.setText(_translate("qosmDialogSettings", "Change", None))
        self.tiletypeRemove.setText(_translate("qosmDialogSettings", "Remove", None))
        self.groupBox.setTitle(_translate("qosmDialogSettings", "More info", None))
        self.label_4.setText(_translate("qosmDialogSettings", "Custom tile types can be added using the layer properties dialog. For a list of commonly used tile types, visit http://wiki.openstreetmap.org/wiki/Tile_servers", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTiletypes), _translate("qosmDialogSettings", "Custom Tile Types", None))
        self.logWhichLog.setItemText(0, _translate("qosmDialogSettings", "Current session", None))
        self.logWhichLog.setItemText(1, _translate("qosmDialogSettings", "Previous session", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLogs), _translate("qosmDialogSettings", "Logs", None))

